spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: '{cipher}980781b4230591d182ab048058961b29b389dc15d2bab216e26ce167a2ae1e81'

token:
  expiration_time: 864000005
  secret: secret

gateway:
  ip: 172.30.1.68